services:
  - type: web
    name: little-lemon-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.10.12"
      - key: ALLOWED_HOSTS
        value: "little-lemon-api.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "http://localhost:5173"
      - key: DATABASE_URL
        fromDatabase:
          name: little-lemon-db
          property: connectionString

databases:
  - name: little-lemon-db
    plan: free
    databaseName: littlelemon
    user: littlelemon